name: NodeJS Angular Dockerized Webapp

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env: 
  REGISTRY: docker.io
  IMAGE_NAME: amario/tradfriui

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
    
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run:  npm install

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log into the Container registry
      uses: docker/login-action@v1 
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Extract metadata for the Docker image
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}


    - name: Build & push Docker image
      uses: docker/build-push-action@v2
      with:
        platforms: linux/arm
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        